'use strict';
let data=null, tab='routes',group='start',query='';
const local=['localhost','127.0.0.1'].includes(location.hostname);
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=s=>s?new Date(s).toLocaleString('ja-JP'):'未実行';
const labels={bug:'! 不具合',ready:'▶ 接続待ち',todo:'○ 未実装',note:'◇ 検討',verify:'? 要確認',passed:'成功',failed:'失敗',running:'実行中','not-run':'未検証',pending:'点検待ち'};
const badge=(level,text)=>`<span class="badge ${esc(level)}">${esc(text||labels[level]||level)}</span>`;
function source(s){if(!s?.file)return '';const label=`${s.file}:${s.line||1}`;
 if(local)return `<button class="source-link" data-source="${esc(s.file)}" data-line="${Number(s.line)||1}">${esc(label)} ↗</button>`;
 if(/^https:\/\/github\.com\/[\w.-]+\/[\w.-]+$/.test(data.source?.repo||'')&&data.source.commit&&data.source.cleanFiles?.[s.file])return `<a class="source-link" href="${esc(data.source.repo)}/blob/${esc(data.source.commit)}/${s.file.split('/').map(encodeURIComponent).join('/')}#L${Number(s.line)||1}" target="_blank" rel="noopener">${esc(label)} ↗</a>`;
 return `<span class="code">${esc(label)} <small>未コミット・公開ソース参照なし</small></span>`;
}
const match=(...items)=>!query||items.join(' ').toLowerCase().includes(query.toLowerCase());
function issues(items){const selected=items.filter(i=>match(i.title,i.description,i.source?.file));return selected.length?selected.map(i=>`<article class="issue"><div>${badge(i.stale?'verify':i.level,i.stale?'? 根拠変化・再確認':null)}</div><div><h3>${esc(i.title)}</h3><p>${esc(i.description)}</p>${source(i.source)}<p class="code">${i.automatic?'自動検出':'登録済み確認事項'} · ${esc(i.id)}</p></div></article>`).join(''):'<p class="empty">この条件の項目はありません。</p>';}
function render(){if(!data)return;
 const bugs=data.issues.filter(i=>i.level==='bug'&&!i.stale).length;
 const stale=Date.now()-new Date(data.heartbeatAt)>120*60000;
 const failed=Object.values(data.tests).some(t=>t.status==='failed');
 const current=Object.values(data.tests).every(t=>!t.fingerprint||t.fingerprint===data.fingerprint);
 const state=data.workerStatus==='error'?'error':stale?'stale':bugs||failed?'bad':data.workerStatus==='testing'?'testing':'observing';
 $('#health').className=`health ${['error','bad'].includes(state)?'bad':state!=='observing'?'warn':''}`;
 $('#health').innerHTML=`<b>${esc({error:'点検処理のエラー',stale:'更新が停止しています',bad:'問題を検出しました',testing:'テストを実行中',observing:'観測中'}[state])}</b><p class="muted">${bugs}件の不具合 / ${data.verify.length}件の要確認<br>検査の範囲内での結果です</p>`;
 $('#revision').innerHTML=`骨組みデモ · ${esc(data.source.branch||'ローカル')} / ${esc(data.source.commit?.slice(0,8)||'版未取得')}${data.source.dirty?' ＋ 未コミット変更':''}<br><span class="code">対象 SHA256 ${esc(data.fingerprint?.slice(0,16)||'未取得')}</span>`;
 $('#alerts').innerHTML=(data.publishError?`<p class="notice error">${esc(data.publishError)}</p>`:'')+(stale?'<p class="notice error">最終確認から2時間以上経過しています。Macの停止・スリープ・同期失敗を確認してください。</p>':'')+(data.workerStatus==='error'?`<p class="notice error">${esc(data.workerError)}</p>`:'')+(!current?'<p class="notice error">テスト結果と点検対象の版が一致しません。成功結果として扱えません。</p>':'')+(data.pendingSource?'<p class="notice">コードの変更を検知しました。最新の静的解析を表示しています。前の版の検証終了を待ち、次のテストを開始します。</p>':'');
 $('#metrics').innerHTML=[[data.coverage.screens||0,'画面'],[data.coverage.operations||0,'静的な操作点'],[data.methods.length,'内部処理'],[bugs,'検出した不具合'],[data.verify.length,'要確認']].map(([n,l],i)=>`<div class="metric ${i===3&&n?'bad':''}"><strong>${n}</strong><span>${l}</span></div>`).join('');
 $('#checked').innerHTML=`最終確認 ${esc(date(data.heartbeatAt))}<br>解析 ${esc(date(data.checkedAt))}`;
 const active=Array.from(document.querySelectorAll('[data-tab]'));active.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tab===tab)));
 $('#run').hidden=!local;$('#run').disabled=data.workerStatus==='testing';
 const sidebarScroll=$('.sidebar')?.scrollTop||0;let html='';
 if(tab==='routes'){
  const groups=data.groups.filter(g=>match(g.title,...g.ops.flatMap(o=>[o.label,o.target,o.owner,...o.effects])));
  const chosen=groups.find(g=>g.id===group)||groups[0];if(chosen)group=chosen.id;
  html=`<div class="route-layout"><aside class="sidebar" aria-label="画面一覧">${groups.map(g=>`<button data-group="${esc(g.id)}" aria-current="${g.id===group}">${esc(g.title)}<small>${g.ops.length}</small></button>`).join('')}</aside><div>${chosen?`<div class="section-head"><h2>${esc(chosen.title)}</h2><span class="muted">${chosen.ops.length}操作点 · 静的推定</span></div>`+chosen.ops.filter(o=>match(chosen.title,o.label,o.target,o.owner,...o.effects)).map((o,i)=>`<article class="op"><div class="op-number">${String(i+1).padStart(2,'0')}</div><div><span class="tag">${esc({action:'クリック',form:'フォーム送信',navigation:'画面を開く',transition:'処理後の遷移',input:'入力・選択'}[o.kind])}</span><div class="op-title">${esc(o.label)}</div>${source(o.source)}</div><div class="evidence">対象 <code>${esc(o.target||'状態・入力によって変わる')}</code><br>${o.dynamic?badge('verify','動的な値・要確認'):o.handler?`処理 ${source(o.handler)}<br>`:''}${o.effects.length?`内部処理 <span class="code">${esc(o.effects.join(' → '))}</span>`:o.kind==='navigation'||o.kind==='transition'?'画面遷移':'<span class="muted">UI状態の更新・委譲を含みます</span>'}</div></article>`).join(''):'<p class="empty">該当画面がありません。</p>'}</div></div>`;
 }else if(tab==='issues')html=`<div class="section-head"><h2>根拠のある問題と未実装</h2><span class="muted">! 不具合 / ▶ 接続待ち / ○ 未実装 / ◇ 検討</span></div>${issues(data.issues)}`;
 else if(tab==='verify')html=`<div class="section-head"><h2>判断・再確認が必要な項目</h2></div><p class="muted">根拠が消えた問題は自動削除せず、ここに保持します。</p>${issues(data.verify)}`;
 else if(tab==='api')html=`<div class="section-head"><h2>HTTP入口と内部処理</h2><span class="muted">実APIとアプリ内メソッドを分けて表示</span></div>${data.http.map(a=>`<p><b>${esc(a.method)}</b> ${esc(a.path)}</p><p class="muted">${esc(a.description)} ${source(a.source)}</p>`).join('')}<div class="table-wrap"><table><thead><tr><th>内部処理</th><th>定義</th><th>静的な呼び出し元</th></tr></thead><tbody>${data.methods.filter(m=>match(m.name,m.file,...m.callers.map(c=>c.owner))).map(m=>`<tr><td><code>${esc(m.name)}()</code></td><td>${source(m.source)}</td><td>${m.callers.length?m.callers.slice(0,10).map(c=>`${esc(c.owner)} ${source(c)}`).join('<br>'):'<span class="muted">repo経由の直接呼出し未検出。this経由・テスト等は要確認</span>'}</td></tr>`).join('')}</tbody></table></div>`;
 else if(tab==='tasks')html=`<h2>定時タスク・イベント</h2><p class="notice">本番の通知スケジューラ・決済Webhook等は未接続です。下記はコードにあるブラウザ側のタイマーとイベントです。Mac停止中は観測の同期も止まります。</p><h3>ブラウザのタイマー</h3><div class="table-wrap"><table><thead><tr><th>処理</th><th>間隔（ms）</th><th>位置</th></tr></thead><tbody>${data.timers.filter(t=>match(t.owner,t.type)).map(t=>`<tr><td>${esc(t.type)} / ${esc(t.owner)}</td><td>${esc(t.delay)}</td><td>${source(t)}</td></tr>`).join('')}</tbody></table></div><h3 style="margin-top:24px">イベント入口</h3>${data.events.filter(e=>match(e.event,e.owner)).map(e=>`<p>${badge('note',e.event)} ${esc(e.owner)} ${source(e)}</p>`).join('')}<p class="muted">観測の同期方式：${esc(data.syncMode)}。最終確認時刻で更新停止を判断してください。</p>`;
 else if(tab==='changes')html=`<h2>前回の解析からの差分</h2><p>${data.changes.baseline?'初回の一覧作成です。':`操作定義 ${data.changes.added}追加 / ${data.changes.removed}削除`}</p><p class="muted">行番号ではなく、ファイル・所有関数・操作種別・対象・ラベルで比較します。</p>${(data.changes.files||[]).filter(f=>match(f)).map(f=>`<p>＋ 更新 ${source({file:f,line:1})}</p>`).join('')}${(data.changes.removedFiles||[]).map(f=>`<p>− 削除 <code>${esc(f)}</code></p>`).join('')}`;
 else if(tab==='tests')html=`<div class="section-head"><h2>固定したコピーでの自動検証</h2><span class="muted">対象アプリの保存データを変更しません</span></div>${Object.entries(data.tests).map(([kind,t])=>`<article class="test-band"><div><h3>${kind==='unit'?'内部ロジック':'ブラウザ操作'}</h3>${badge(t.status)} ${t.fingerprint!==data.fingerprint?badge('verify','別の版'):''}</div><div><p>${t.reason?esc(t.reason):`${t.passed||0}成功 / ${t.failed||0}失敗 / ${t.total||0}件${t.status==='running'?`（${t.completed||0}完了）`:''}`}</p><p class="code">SHA256 ${esc(t.fingerprint?.slice(0,16)||'未取得')}</p><p class="muted">${esc(date(t.finishedAt||t.startedAt))}</p>${(t.failures||[]).map(f=>`<p>${badge('bug','失敗')} ${esc(f.name)} ${source(f.source)}</p>`).join('')}</div><strong>${t.passed||0}<span class="muted"> / ${t.total||0}</span></strong></article>`).join('')}<p class="notice">テストが成功しても、未作成のテストや未確定の仕様まで正しいとは判断できません。ソース本文・入力値・生ログは公開しません。</p>`;
 else if(tab==='overview')html=`<h2>現在の実装構成</h2><p class="muted">実装済みの構成とimport関係から作成。外部サービスの接続を推測で追加しません。</p><section class="architecture"><div class="flow"><div class="flow-node"><b>画面・操作</b><small>${data.coverage.screens}画面 / ${data.coverage.operations}操作点</small>${source({file:'dist/app.js',line:1})}</div><span class="flow-arrow">→</span><div class="flow-node"><b>クリック・フォームの委譲</b><small>action / submitForm</small></div><span class="flow-arrow">→</span><div class="flow-node"><b>DemoRepository</b><small>権限・状態・履歴の模擬処理</small>${source({file:'dist/model.js',line:1})}</div><span class="flow-arrow">→</span><div class="flow-node"><b>localStorage</b><small>デモ会員・履歴の保存</small></div></div><div class="split-line"><b>会員登録デモ</b> → RegistrationDemo → 一時メモリ（登録回答を保存・送信しない）</div><div class="split-line"><b>静的サーバー</b> → HTML / CSS / JavaScript配信。業務API・実認証・実決済・実審査は未接続。</div></section><h3>コード上のimport関係</h3><div class="table-wrap"><table><thead><tr><th>呼び出し元</th><th>読み込むモジュール</th></tr></thead><tbody>${data.imports.filter(i=>i.file.startsWith('dist/')&&match(i.file,i.target)).map(i=>`<tr><td>${source(i)}</td><td>${source({file:i.target,line:1})}</td></tr>`).join('')}</tbody></table></div>`;
 $('#content').innerHTML=html;if($('.sidebar'))$('.sidebar').scrollTop=sidebarScroll;
}
async function load(){try{const r=await fetch(`audit.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error();const next=await r.json();if(next.schema!==1)throw new Error();data=next;render();}catch{$('#alerts').innerHTML='<p class="notice error">点検データを読み込めません。通信・公開状態を確認して再読み込みしてください。表示中の結果は更新されていません。</p>';}}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;
 if(b.dataset.tab){tab=b.dataset.tab;render();}else if(b.dataset.group){group=b.dataset.group;render();}
 else if(b.id==='refresh')await load();else if(b.id==='close')$('#source').close();
 else if(b.dataset.source&&local){try{const r=await fetch(`/source?file=${encodeURIComponent(b.dataset.source)}&hash=${data.fingerprint}`);if(!r.ok)throw new Error();const s=await r.json();$('#source-title').textContent=b.dataset.source+':'+b.dataset.line;$('#source-code').innerHTML=s.text.split('\n').map((line,i)=>`<span class="source-line ${i+1===Number(b.dataset.line)?'selected':''}">${String(i+1).padStart(4,' ')}  ${esc(line)}</span>`).join('');$('#source').showModal();$('#source-code .selected')?.scrollIntoView({block:'center'});}catch{$('#alerts').innerHTML='<p class="notice error">表示中の版のソースを取得できません。再読み込みして確認してください。</p>';}}
 else if(b.id==='run'&&local){b.disabled=true;try{const r=await fetch('/refresh',{method:'POST'});if(!r.ok)throw new Error();setTimeout(load,400);}catch{$('#alerts').innerHTML='<p class="notice error">点検を開始できませんでした。</p>';b.disabled=false;}}
});
$('#search').addEventListener('input',e=>{query=e.target.value;render();});
load();setInterval(load,10000);
